### ISSUE TITLE
Provide volunteers with a super simple hosting option

### ISSUE THREAD

**Issue by andylolz** [CodeClub/ideas#1]
There are several emails on the volunteer google groups about teepee.io no longer being available. Regardless of teepee, though, it might be good to offer a @codeclub hosted alternative.

[Here’s a good thread about hosting](https://groups.google.com/forum/#!msg/greaterlondoncodeclub/8zyJK8YPAzw/4lsn0qNDmHUJ) on the Greater London Code Club mailing list.

**Comment by laurakirsop** [comment]
Defo this too, we're talking to Teepee at the mo about yoinking their code :)

**Comment by immunda** [comment]
(This would be dope :+1: )

**Comment by andylolz** [comment]
Oooh – teepee letting us yoink their code would be ideal here.

I’ll also look into open source options for a nice interface on some cloud service that we could bolt code club authentication onto.

**Comment by andylolz** [comment]
I’m running JS Bin on heroku here:
http://web.treadsoft.ly
I’m working on simplifying it right down so it’s just the stuff needed for web curriculum stuff.

**Comment by martinpeck** [comment]
I'm not at all sure what the aim is here.
What is it you're hoping to build, and when you've built it what happens to that service/prototype?

**Comment by andylolz** [comment]
Currently, I’m using this in my own club for web projects – as a replacement for Trinket. That’s because various Trinket features don’t work on the version of Chrome we use at my club – most notably the save feature (which is a deal breaker.)

JS Bin also provides a URL for the project output (e.g. [like this](http://web.treadsoft.ly/six/quiet)), which Trinket doesn’t currently provide. Without this, it all feels sandboxed and separated from the actual purpose, since it’s completely unclear that the browser can actually render HTML.

I’ve also [begun using this for hosting](http://web.treadsoft.ly/kuv), which relates specifically to this ticket.

If Code Club OAuth existed, I’d add that, and provide this as a service for other volunteers to use.

**Comment by CodeClubRik** [comment]
Hey @andylolz  -- in terms of trinket features that don't work -- if you could let me know what those non-working features are, I'm sure I can send them over to trinket to look at.

Trinket do have separate URLs for output-only. I'm not sure what they are off the top of my head, but I can ask when I send on your feedback.

**Comment by andylolz** [comment]
I’ve already sent some feedback to Trinket about issues I’m having. In IE10 (Win7):
 * I can’t save trinkets. The save button permanently looks like this:
   ![screen shot 2015-06-26 at 15 52 00](https://cloud.githubusercontent.com/assets/464193/8380107/ed1384fc-1c1b-11e5-87d5-b92025aa4da1.png)
 * When I click to change the name of the trinket, the text I’m writing isn’t visible:
   ![screen shot 2015-06-26 at 15 52 16](https://cloud.githubusercontent.com/assets/464193/8380119/fcdeb4f6-1c1b-11e5-9ab3-aec15bb938b7.png)

It also seems that In IE9 (Win7) it’s not possible to create a new trinket? Just seem to be redirected to: https://trinket.io/library/#!/trinkets/create?lang=python

I’ve just had another look for output-only URLs, and I can’t find them. I’ve already contacted trinket about this, but you’re welcome to try too.

I’m going to close this issue, as I don’t get the impression there’s any appetite for this.
