### ISSUE TITLE
Paginate web versions of projects

### ISSUE THREAD

**Issue by andylolz** [CodeClub/ideas#5]
This is super specific to `codeclub/lesson_format`. But adding it here because it relates to #4.

For the student version in particular (described in #4) it would be cool to paginate the html version to make it easier to keep track of progress.

This could be implemented in javascript (so loading the next page wouldn’t require an internet connection). The no-js fallback would be the non-paginated version.

**Comment by andylolz** [comment]
@CodeClubRik: There’s a (very basic) demo of this here:
http://treadsoft.ly/CodeClubUK-Projects/en-GB/01_scratch_01/03/Balloons.html#page-intro

**Comment by CodeClubRik** [comment]
That's awesome!

What's also cool is that the pagination has anchors `.../#page-2` etc. so we can now easily reference specific activities in other projects.

Currently the pagination is per-activity, but for longer steps could we also paginate per step, or per n-steps, etc?

**Comment by andylolz** [comment]
> Currently the pagination is per-activity, but for longer steps could we also paginate per step, or per n-steps, etc?

We could… But I wonder if that’s an indication that the step should be split into multiple steps?

I basically quite the trick of imposing restrictions on what the project creator can do, in order to force convention / standardisation (because I’m working on the assumption that those are good things for the projects as a whole, and make it easier for the learner). However, that might be a false assumption… And I don’t want to make your job harder! So if it is a pain for you, then yes it could totally work a different way :)

**Comment by andylolz** [comment]
Oh wait… Perhaps I’ve misunderstood. The pagination is currently per step. In fact, perhaps the hash should say e.g. `…/#step-2` instead of `…/#page-2`, in order to make this a bit clearer.

**Comment by CodeClubRik** [comment]
> perhaps the hash should say e.g. …/#step-2 instead of …/#page-2, in order to make this a bit clearer.
yeah that would be good.

...and I agree with you about making sure that steps are kept short. :)

**Comment by andylolz** [comment]
Okay – fixed it so they’re called steps in the hash now:
http://treadsoft.ly/CodeClubUK-Projects/en-GB/01_scratch_01/03/Balloons.html#step-intro

**Comment by CodeClubRik** [comment]
I really like this!!
I also love the progress bar idea, and wonder whether it would be helpful (or not!) to add the name of the previous/next steps by the buttons? would this just complicate things?

**Comment by andylolz** [comment]
Discussion in CodeClub/lesson_format#159 suggests this is either logged elsewhere, or it’s not on the cards. Closing.
